supabase/realtime-js

.github/workflows/continuous-integration-workflow.yml

Bug fix, feature, docs update, ...
Fix #6 possibly. Check for more details first.
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

Add GitHub Actions  test runner

---

README.md

The syntax for importing the module seems to be wrong

Fix syntax in example

---

test/channel_test.js
test/socket_test.js

I had made a wrong diagnosis previously. The tests did not complete because of the missing -exit flag. Skipped tests are okay. 
Uncommenting the skipped tests.

uncomment skipped tests

---

README.md

I was able to subscribe to all realtime changes by specifying the * at the end

Update minor documentation error

---

package.json
src/RealtimeClient.ts

closes #78 
Not supported by IE 11, but can be added w/ polyfills

feat: replace query-string w/ URLSearchParams

---

README.md

docs update
`realtime:{schema}:{table}:{col}.eq.{val}`
`realtime:{schema}:{table}:{col}=eq.{val}`

Docs: update row level change topic format

---

README.md
example/README.md

docs update
Related issue: https://github.com/supabase/realtime/issues/165

docs: specify ws and wss urls

---

src/RealtimeClient.ts

Bug fix
heartbeat messages are not pushed to server
heartbeat messages are pushed to server

fix: add back heartbeat message push

---

package-lock.json
package.json
src/RealtimePresence.ts
src/index.ts
test/presence_test.js

feature
add presence functionality

feat: add presence

---

package-lock.json
package.json

Since we're importing the types

fix: include @types/phoenix as dependencies

---

package.json

fix: types in package.json

---

src/RealtimeChannel.ts
src/RealtimeClient.ts
src/RealtimePresence.ts
test/presence_test.js

feature
Add `RealtimeChannel` for broadcast and presence support and update `RealtimeClient` to include `RealtimeChannel` while maintaining backwards compatibility.

Add RealtimeChannel to enable broadcast and presence

---

README.md
example/pages/index.js
src/RealtimeChannel.ts
src/RealtimeClient.ts
src/RealtimePresence.ts
src/index.ts
src/lib/push.ts
test/channel_test.js
test/presence_test.js
test/socket_test.js

Chore
Improve and export Realtime types for v2 release.

chore: improve v2 types

---

src/RealtimeChannel.ts
src/RealtimeClient.ts
src/RealtimePresence.ts

docs update
Private methods do not show up in docs.

docs: hide private methods from docs

---

README.md

docs update
Update the README to reflect the new v2 API.
See https://github.com/supabase/realtime-js/tree/docs/readme-v2 for README.

docs: update v2 README

---

README.md

Docs update
Addresses https://github.com/supabase/realtime-js/issues/227

docs: update channel config in README

---

package-lock.json
package.json

Bug fix
Addresses:
- https://github.com/supabase/realtime-js/security/dependabot/29
- https://github.com/supabase/realtime-js/security/dependabot/28
- https://github.com/supabase/realtime-js/security/dependabot/27
- https://github.com/supabase/realtime-js/security/dependabot/24
- https://github.com/supabase/realtime-js/security/dependabot/15

fix: upgrade vulnerable dependency versions

---

src/RealtimeChannel.ts

Added more information about the arguments for channel.send()
Had to change the payload name since it could potentially conflict with the name within the object

fix: Enrich send function arguments

---

package-lock.json
package.json

Seems this dependency is no longer necessary since #263.

Ditch @types/websocket dependency

---

package-lock.json
package.json
src/RealtimeClient.ts
test/socket_test.js

Bug fix
Breaks: https://github.com/supabase/realtime-js/issues/266
Works for all envs.

fix: replace ws require with import

---

src/RealtimeClient.ts
test/socket_test.js

Remove Private from function signature

fix: Remove Private from function signature

---

src/RealtimeChannel.ts
src/RealtimeClient.ts
test/socket_test.js

Handle properly jwt tokens as currently we were using only the apikey and that is not enough for scenarios with RLS policies.

fix: Handle properly jwt tokens

---

src/RealtimeClient.ts
test/socket_test.js

URL on fetch requests for channels

fix: URL on fetch requests for channels

---

src/RealtimeClient.ts

fix: Remove console.log

---

src/RealtimeChannel.ts
test/channel_test.js

Fixes the failing CI check [here](https://github.com/supabase/realtime-js/actions/runs/9483220781)

fix: update asserts

---

src/RealtimeChannel.ts
test/channel_test.js

fix: Send proper configuration

---

README.md

feat: Release Realtime 2.10.0

---

package-lock.json

fix: Update dependencies

---

src/RealtimeClient.ts

Create default web worker without fetch. Also we use the defined fetch to gather the worker.js script and load it as a blob.

fix: Create default webworker without fetch

---

.github/workflows/ci.yml
package-lock.json
package.json
test/channel.test.ts

Remove Module type from package.json. Also adds `arethetypeswrong/cli` to avoid future regressions regarding this type of issues
Also noticed that we were not running any CI for PRs. Fixed that

fix: Remove Module type from package.json

---

package-lock.json
package.json
src/RealtimeClient.ts
test/channel.test.ts
tsconfig.json

Adds Web Workers as a way to run heart beat on Realtime to avoid suspending the tab.

fix: Add Web Workers as a way to run health check

---

src/RealtimeClient.ts

Improve error message on invalid JWT

fix: Improve error message on invalid JWT

---

src/RealtimeClient.ts

fix: set proper type in options

---

.github/workflows/ci.yml
vitest.config.ts

Upload coverage report to coveralls, check https://coveralls.io/github/supabase/realtime-js for uploaded report.

ci: upload coverage to coveralls

---

src/RealtimeClient.ts
src/lib/constants.ts
test/client.test.ts

fix: properly export log level

---

src/RealtimeClient.ts
test/channel.test.ts

move back to an array solution

fix: move back to an array solution

---

package-lock.json
package.json
pnpm-lock.yaml
src/RealtimeClient.ts
src/WebSocket.browser.ts
src/WebSocket.native.ts
src/WebSocket.node.ts
src/WebSocket.ts

properly handle ws browser export

fix: properly handle ws browser export

---

src/RealtimeClient.ts

Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

fix: adopt isomorphic websocket implementation

---

src/RealtimeChannel.ts
src/RealtimeClient.ts
test/RealtimeChannel.test.ts
test/RealtimeClient.test.ts
test/ReconnectionLogic.test.ts
test/helpers/testHelpers.ts

Improves readability and testing

Fix: readability and testing

---

src/RealtimeChannel.ts
src/RealtimeClient.ts
test/RealtimeChannel.test.ts
test/RealtimeClient.test.ts
test/ReconnectionLogic.test.ts
test/helpers/testHelpers.ts
test/push.test.ts

make apikey mandatory; improve stability and readability of code

feat: make apikey mandatory; improve stability and readability of code

---

src/RealtimeClient.ts
test/RealtimeClient.heartbeatCallback.test.ts
test/RealtimeClient.lifecycle.test.ts
test/helpers/lifecycle.ts

fix: add hearthbeat callback
