supabase/realtime-js

- README.md
docs update
Add instruction to pass in token for when Realtime server is running in secure mode.
Related issue: https://github.com/supabase/realtime/issues/109
> docs: add instruction to pass in token for JWT auth

- README.md
docs update
Specifies RealtimeClient param key is `token`
Specifies RealtimeClient param key is `apikey`
Related issue: [Phoenix tokens for channel auth #95
](https://github.com/supabase/realtime/issues/95)
Related comment: https://github.com/supabase/realtime/issues/95#issuecomment-777868713
**NOTE**:
Should be merged when [feat: change socket param from token to apikey #122](https://github.com/supabase/realtime/pull/122) has been merged to `master`.
> docs: update RealtimeClient param key from token to apikey

- src/RealtimeSubscription.ts
- test/channel_test.js
A proposal on reducing traffic twice by implementing the "bind all events" only on the client. No need more send events with "*", after that fix, you could remove `RealtimeWeb.Endpoint.broadcast_from!(self(), topic, "*", txn)` in the `RealtimeWeb.RealtimeChannel.handle_realtime_transaction`
In current behavior, the server always sends two messages, were different only in event name. On the client-side simple check matching by event name.
The new behavior can bind all events where the event name equals type in the payload.
Example of current event
```json
{
"event": "INSERT",
"payload": {
"columns": [],
"commit_timestamp": "2021-02-12T16:03:31Z",
"record":{},
"schema": "public",
"table": "users",
"type": "INSERT"
},
"ref": null,
"topic": "realtime:*"
}
``` …
> Client functionality of bind all events

- src/RealtimeClient.ts
- src/lib/serializer.ts
- test/socket_test.js
feature
Client can only decode json messages
Client can decode both json and binary messages
Related: https://github.com/supabase/realtime/pull/131
> Add serializer to decode binary messages

- src/RealtimeClient.ts
- test/socket_test.js
Bug fix
Large influx of messages prevents heartbeat reply which forces client to re-connect. As a result, client stops receiving messages after re-connect.
Related issue: #77 
Client no longer re-connects when there is a large influx of messages. As a result, client receives all messages sent from server.
This solution was proposed by @abc3 on issue #77.
Although heartbeat can be reset whenever any message comes in, this limits the scope to only specific realtime db change messages where `event`(e.g. `"INSERT"`) aligns with the payload's `type` (e.g. `"INSERT"`).
> fix: large influx of messages prevents heartbeat reply

- test/channel_test.js
Bug fix where the ignoredSpy was not being used.
This test checks if `ignoredSpy` had been called at the end, but since `ignoredSpy` has not been bound to any event subscription, it won't be called for any event triggers. Binding it to `otherEvent` will properly test this case. 
```javascript
it('other event callbacks are ignored', () => {
const spy = sinon.spy()
const ignoredSpy = sinon.spy()
channel.trigger('event', {}, defaultRef)
assert.ok(!ignoredSpy.called)
channel.on('event', spy)
channel.on('otherEvent', ignoredSpy) // Newly Added line
channel.trigger('event', {}, defaultRef)
assert.ok(!ignoredSpy.called)
})
```
I stumbled across this test code, and decided to open a PR, but apologies if I am missing some context and this code is working without the code that I added.
> Making sure callback set on other events are not called for certain event

- package-lock.json
- package.json
Removes an unnecessary runtime dependency installation
Installing `@supabase/realtime-js` installs `@types/websocket` which has no runtime functionality.
Installing `@supabase/realtime-js` only installs `websocket` as a dependency.
Typically packages that are written in typescript only include type definitions as devDependencies.
> Move @types/websocket from dependencies to devDependencies

- src/RealtimeClient.ts
This PR is in preparation for plumbing options through `SupabaseClient`. We need the options type exported to make TypeScript happy and not duplicate the type.
> Export type Options

- package-lock.json
- package.json
- src/index.ts
[This PR](https://github.com/supabase/realtime-js/pull/95) didn't quite work right. Two issues: 
1. `@types/websocket` is an actual dependency but marked as devDep
2. It's easier on devs if we re-export from index.d.ts
> fix: type export issues

- package.json
- src/RealtimeClient.ts
- src/RealtimeSubscription.ts
- src/lib/push.ts
- test/channel_test.js
- test/socket_test.js
It clears timeouts and intervals when calling `disconnect()`
When including `realtime-js` as a dependency, there's no way to close timeouts and intervals, leaving open handles.
This project has solved this issue on the tests using a mocha `--exit` flag but that is not an option for downstream modules that want to avoid leaks.
This PR updates the tests in realtime-js to call `disconnect()` after each test. Users of this module should do the same when testing and cleanly shutting down servers.
This PR should also help fix https://github.com/supabase/supabase-js/issues/44 without `process.exit()` hacks.
> Close open handles to allow testing without --exit flag

- src/RealtimeClient.ts
- src/lib/constants.ts
- test/socket_test.js
Security feature
Latest access token is sent to the server at regular heartbeats.
> feat: push access token to every channel during heartbeat

- src/RealtimeClient.ts
- test/socket_test.js
Bug fix
`access_token` message is pushed to channels that have not been joined yet.
`access_token` message is pushed only to joined channels.
> fix: push access token only to joined channels

- README.md
Update README to reflect that `Response` type will have `errors` due to the new Realtime security (WALRUS)
> chore: add errors to Response type in README

- package-lock.json
- src/RealtimeClient.ts
- src/RealtimeSubscription.ts
- src/lib/push.ts
- test/channel_test.js
- test/push.test.js
- test/socket_test.js
Bug fix
Channel (subscription) is created with `user_token` with an expiration that never gets updated with `setAuth` (never refreshed). No successful reconnection after `user_token` has expired even though `supabase-js` is calling `setAuth` with refreshed token.
`setAuth` will update each channel's join payload with the latest `user_token`.
Related issue: https://github.com/supabase/realtime-js/issues/123
> fix: update channel join payload for successful reconnect

- src/RealtimeClient.ts
- src/RealtimeSubscription.ts
- test/channel_test.js
- test/socket_test.js
Bug fix
Client can create duplicate subscriptions by listening to the same topic.
Client can create one subscription for each unique topic.
Fixes: https://github.com/supabase/realtime-js/issues/127
> fix: force client to listen to unique subscriptions

- src/RealtimeClient.ts
- test/socket_test.js
Bug fix
client resets heartbeat message send interval on received message so another heartbeat message is not sent to server. this results in reconnection and lost database change messages when server has reached socket connection timeout limit.
client resets pendingHeartbeatRef to `null` but will not reset heartbeat message send interval so client continues to send heartbeat message at a regular interval.
Related issues:
- https://github.com/supabase/realtime-js/issues/94
- https://github.com/supabase/supabase/issues/5290#issuecomment-1045121578
- https://github.com/supabase/realtime-js/issues/133
> fix: set heartbeat ref to null on incoming message

- package-lock.json
- package.json
- src/RealtimeChannel.ts
- src/RealtimePresence.ts
- test/presence_test.js
Bug fix
Lodash methods do not work with Nuxt 3 out of the box.
Removing Lodash methods and replace them with vanilla JS.
- https://github.com/supabase/realtime-js/issues/148
- https://github.com/supabase/realtime-js/issues/149
> fix: remove lodash clonedeep and isequal

- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- test/presence_test.js
feature
Use `vsndate` url query params to determine whether to instantiate RealtimeSubscription or RealtimeChannel.
> feat: use channel or subscription depending on versionDate

- src/RealtimeClient.ts
Bug fix
this.versionDate is only set when `vsndate` query param is a valid date.
> fix: update logic that sets versionDate in RealtimeClient instance

- src/RealtimeClient.ts
Bug fix
Use of `URL` to get `vsndate` query param is broken in React Native since URL needs a polyfill.
Just works.
Related discussion: https://github.com/supabase/supabase/discussions/6522#discussioncomment-2616398
> fix: remove URL instance with vsndate from params

- src/RealtimeClient.ts
- src/lib/push.ts
- test/channel_test.js
Bug fix
Devs who are using React 18 in strict mode in development are having their subscriptions closed.
Devs who are using React 18 in strict mode in development are able to maintain a joined and open subscription.
Addresses: https://github.com/supabase/realtime-js/issues/169
This is a cherry pick from `rc` branch: https://github.com/supabase/realtime-js/commit/c32db96f87023dceaaccc5f081e0bda5c5e5b9be
> fix: keep second channel with same topic open on rapid re-subscribe

- src/RealtimeChannel.ts
Types improvement
Incomplete types for postgres changes events.
Example from Redux Toolkit (inside the `onCacheEntryAdded` callback)
```ts
const channel = supabase
.channel('db-messages')
.on<Post>(
'postgres_changes',
{ event: '*', schema: 'public', table: 'posts' },
(payload) =>
updateCachedData((draft) => {
if (payload.eventType === 'INSERT') {
postsAdapter.addOne(draft, payload.new);
// Argument of type '{} | Post' is not assignable to parameter of type 'Post'.
}
if (payload.eventType === 'UPDATE') {
postsAdapter.updateOne(draft, {
id: payload.new.id, // Property 'id' does not exist on type '{} | Post'.
changes: payload.new,
});
}
if (payload.eventType === 'DELETE') {
postsAdapter.removeOne(draft, payload.old.id);
// Property 'id' does not exist on type '{} | Partial<Post>'.
}
}),
) …
```
> fix: improve realtime postgres changes types

- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- src/RealtimePresence.ts
Added comments to methods and added @internal to ignore private methods in documentation.
Run command `yarn docs`. This command will create v2 version document. 
The document includes internal/private methods - thus making it hard to read.
Run `yarn docs.` This should hide internal/private methods and show comments to method.
Add any other context or screenshots.
> Added @internal flag to ignore private methods into TypeDocs/ Added method comments.

- src/RealtimeChannel.ts
- src/RealtimeClient.ts
docs update
Add jsdoc for `RealtimeChannel.on`, `RealtimeClient.getChannels`, `RealtimeClient.removeChannel`, `RealtimeClient.removeAllChannels`.
> docs: add jsdoc for the widely used methods

- README.md
- src/RealtimeClient.ts
feature
Enable disabling of the throttle, default is 10, by passing in a negative number for `eventsPerSecond`.
Addresses: https://github.com/supabase/realtime-js/issues/220
> feat: disable throttle with negative eventsPerSecond number

- src/RealtimeChannel.ts
- src/RealtimePresence.ts
Update types for `channel.presenceState()` to allow users to pass a type for their state. This will stop users having to cast the state on usuage.
Not able to pass the presence state type to channel.presenceState()
N/A
Fixes #223
> Allow consumers to pass presence state types to channel.presenceState

- src/RealtimeClient.ts
- test/channel_test.js
Fixes the issue where using Supabase realtime without signing in sends `null` access token to the server. 
Currently, `accessToken` of `RealtimeClient` class is only set within `setAuth`, but if the user is not signed in via Supabase Auth, `realtime.setAuth` is never called, hence resulting in `null` `accessToken` value. 
This PR updates `RealtimeClient` to use the `apikey`, which contains either the anonkey or the service role key as the initial value of `accessToken`.
> fix: set initial access token

- package-lock.json
- package.json
- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- test/channel_test.js
- tsconfig.json
- tsconfig.module.json
feature
Enables sending messages to server via a broadcast HTTP endpoint request instead of waiting for a WebSocket connection, subscribing to a channel, and then sending messages.
```js
import { RealtimeClient } from '@supabase/realtime-js'
const client = new RealtimeClient(REALTIME_URL, {
params: {
apikey: API_KEY
},
})
const channel = client.channel('test-channel')
// No need to subscribe to channel
channel.send({
type: 'broadcast',
event: 'test',
payload: { message: "Hi" }
).then(resp => { console.log(resp) })
// Remember to clean up the channel
client.removeChannel(channel)
```
> feat: send messages via broadcast endpoint

- README.md
- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- src/lib/push.ts
- test/channel_test.js
fix
There's a rate limiter in place that allows one event every 100 milliseconds but this can be customized.
There is no rate limiter.
> fix: remove rate limiter

- src/RealtimeChannel.ts
Add missing `on` overload for Broadcasts
Example code was causing issues to user in https://github.com/supabase/realtime-js/issues/259
> fix: Add missing `on` overload for Broadcasts

- src/RealtimeChannel.ts
- src/RealtimeClient.ts
Bug fix
Instead of using `anon key` it uses user `accessToken`
https://github.com/supabase/realtime-js/issues/271
Channel.send() via REST api works as expected
> fix: channel.send() via REST api

- .github/workflows/release.yml
Chore
Pushing to `next` branch will generate npm next prereleases
https://github.com/supabase/supabase-js/pull/454#issue-1262744424
> chore: sets up next branch as npm prerelease

- src/RealtimeChannel.ts
Bug fix
Realtime server can send `error` on Presence tracking and client does not accept it.
Realtime server can send `error` on Presence tracking and client accepts it and resolves; provides proper feedback to clients.
Related: https://github.com/supabase/realtime/pull/844
> fix: accept error message from server when tracking Presence

- .babelrc
- .npmignore
- package-lock.json
- package.json
Bug fix
Babel dependencies depend on babel-traverse < 7.23.2 which has a security vulnerability.
Remove Babel entirely.
https://github.com/supabase/realtime-js/security/dependabot/40
> fix: remove babel dev dependencies

- package-lock.json
> fix: Bump WS dependency due to CVE

- src/RealtimeChannel.ts
Close fetch response on HTTP broadcast sent
> fix: Close fetch response on HTTP broadcast sent

- src/RealtimeChannel.ts
- test/channel_test.js
Broadcast endpoint includes private param in request body
> fix: Broadcast endpoint includes private param in request body

- package-lock.json
- package.json
- src/RealtimeClient.ts
- test/channel.test.ts
- tsconfig.json
Added capacity to use Worker for Healthchecks. We also allow users to override the worker URL so they are able to modify it as they see fit
> add: Worker for Healthcheck

- src/RealtimeChannel.ts
- tsconfig.json
To help users debug issues and avoid type errors we're adding system as a type of message users can add `on` callbacks
> fix: Add type to system messages

- package-lock.json
- package.json
- src/RealtimeClient.ts
- test/socket.test.ts
code does a quick check on the exp of a token to prevent it from being sent to realtime
> fix: prevent sending expired tokens

- src/RealtimeClient.ts
- test/channel.test.ts
Access token callback can be null
> fix: Access token callback can be null

- src/RealtimeClient.ts
- test/channel.test.ts
> fix: Release new version

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- src/RealtimeClient.ts
- src/lib/constants.ts
- test/socket.test.ts
* remove client side check of jwt token
* await on setAuth in heartbeat
* send lib version on setAuth
* only send token on setAuth if token has changed
> fix: remove client side check of jwt token

- src/RealtimeClient.ts
- test/socket.test.ts
Change format of version sent to `realtime-js/0.0.0-automated`
> fix: Change format of version sent

- src/RealtimeClient.ts
- src/lib/constants.ts
- test/client.test.ts
* Deprecation of log_level to logLevel
* Exports type of log level supported
* Fixes log level being sent in URL params
* Changes heartbeat to default to 25s
> fix: set log level on params

- src/RealtimeChannel.ts
- test/channel.test.ts
set proper error states on error
> fix: set proper error states on error

- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- test/channel.test.ts
stop push timers on disconnect
> fix: stop push timers on disconnect

- package.json
- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- src/WebSocket.native.ts
- src/WebSocket.ts
- test/channel.test.ts
* adds on heartbeat callback
* sets 25s as default for heartbeat timer
* improvements with Expo compatibility
* improvements on channel teardown
> fix: onHeartbeat; Expo comparability;  general improvements (#469)

- package.json
Bug fix
In Deno 1 (edge-runtime <= 1.67.4), there seems to be an issue when importing node packages in import (es module) mode, so I guess the require (commonjs) should be the default.
Context: https://supabase.slack.com/archives/C037QCFELUR/p1748899818102949?thread_ts=1748869838.255779&cid=C037QCFELUR
> fix: make the exports section compatible with Deno 1

- package.json
Updates package.json exports to default to the ESM build instead of CommonJS, resolving "Critical dependency: the request of a dependency is an expression" warnings in webpack builds.
Changes:
- Set "default" to ESM build (./dist/module/) preserving native import()
- Add explicit "import" condition for ESM-aware bundlers
- Add "types" condition for better TypeScript resolution
- Keep "require" pointing to CommonJS for Node.js compatibility
Tested on Next.js v15 with webpack (non-turbopack). Previous workaround required manual webpack config:
```js
webpack: (config) => {
config.resolve.mainFields = ['browser', 'module', 'main'];
config.resolve.conditionNames = ['browser', 'module', 'import', 'default'];
return config;
}
```
This exports change eliminates the need for manual webpack …
> fix: prioritize ESM build in package exports to fix webpack warnings

- src/RealtimeChannel.ts
- src/RealtimeClient.ts
- test/channel.test.ts
- test/client.test.ts
on multiple subscribe calls, we ignore if we do not need to act instead of raising an exception
it also removes a line of code that was creating issues on channel removal: https://github.com/supabase/realtime-js/pull/488
> fix: handle subscribed called multiple times; remove redundant line

- package-lock.json
- package.json
- pnpm-lock.yaml
Hot fix for missing peer dependency (`ws` is resolved as `peerDependency` for `isows`)
Newest package release fails during usage due to missing peer dependency (`ws`)
The peer dependency is installed within the `realtime-js`
`supabase-js` issue: https://github.com/supabase/supabase-js/issues/1462
> fix: resolve 'ws' peer dependency

- src/RealtimeClient.ts
- src/lib/constants.ts
- test/RealtimeClient.test.ts
starts deprecation of the headers option as now the option won't impact anything in the code
version will be sent in the payload to ensure we still are able to check which version of the client lib is used
> fix: soft deprecation of headers and simplify ws socket connection

- src/RealtimeChannel.ts
- src/RealtimePresence.ts
- test/RealtimeChannel.test.ts
- test/RealtimeClient.test.ts
Changes the join payload to include a flag to enable/disable presence features. The flag is automatically set if we find a callback for any event of type `presence`.
Cleaned up tests to also be more inline with the expected types.
> feat: Presence enabled flag on join payload

- src/RealtimeClient.ts
- test/RealtimeChannel.test.ts
- test/RealtimeClient.test.ts
Set auth on connect and reconnect flows.
I've also changed the tests to focus on using WS events instead of calling private methods
> fix: Set auth on connect and reconnect flows

- src/RealtimeClient.ts
- test/RealtimeChannel.test.ts
Ensure we call setAuth on connect before any other action and test it
> fix: call setAuth on subscribe

- package-lock.json
- package.json
- pnpm-lock.yaml
- src/RealtimeClient.ts
- src/index.ts
- src/lib/websocket-factory.ts
- test/RealtimeClient.test.ts
- test/websocket-factory.test.ts
Feature - WebSocket compatibility improvement
The realtime-js client uses `isows` for WebSocket support, which has limitations and causes deployment issues:
- **Bundle size issues**: `isows` adds unnecessary weight to browser bundles
- **Limited Node.js support**: Doesn't handle all Node.js versions optimally (especially Node.js 22+ with native WebSocket)
- **Edge runtime incompatibility**: Fails in Cloudflare Workers and Vercel Edge functions
- **Deployment failures**: Causes "Cannot find package 'isows'" errors in production environments like GCP Cloud Run (see [#1470](https://github.com/supabase/supabase-js/issues/1470))
- **Deployment complexity**: Bundlers sometimes struggle with the isows conditional imports
Replaced `isows` with a custom `WebSocketFactory` that provides universal …
> feat: replace isows with native WebSocket factory

- .github/workflows/preview-release.yml
CI/CD enhancement - Improves the preview release workflow and cross-repository testing integration.
- Preview releases are created but there's no automated way to test compatibility with downstream packages
- No cross-repository testing between `realtime-js` and `supabase-js`
- Manual testing required to verify changes don't break integration points
- Limited feedback loop for developers on cross-package compatibility
- **Automated Cross-Repo Testing**: Preview releases automatically trigger compatibility tests in `supabase-js`
- **Smart Triggering**: Only runs on actual source code changes (src/, package files, tsconfig) to avoid unnecessary builds
- **Enhanced Control**: Manual workflow dispatch with configurable options for target branch and test triggering
- **Better UX**: PR comments …
> chore: trigger external tests on supabase-js

- src/lib/transformers.ts
- test/transformers.test.ts
Bug fix
When a record is changed, and that record is used by a row-level access policy, the record arriving in the subscription can be null. When convertChangeData tries to Object.keys(record), we get error:
```
@supabase_supabase-js.js?v=02935ef6:1614 Uncaught TypeError: Cannot convert undefined or null to object
at Object.keys (<anonymous>)
at convertChangeData (@supabase_supabase-js.js?v=02935ef6:1614:17)
at _RealtimeChannel._getPayloadRecords (@supabase_supabase-js.js?v=02935ef6:2552:21)
at @supabase_supabase-js.js?v=02935ef6:2438:83
at Array.map (<anonymous>)
at _RealtimeChannel._trigger (@supabase_supabase-js.js?v=02935ef6:2425:10)
at @supabase_supabase-js.js?v=02935ef6:2947:96
at Array.forEach (<anonymous>)
at @supabase_supabase-js.js?v=02935ef6:2947:67
at Serializer.decode …
```
> fix(realtime): handle null at convertChangeData
